version: '3.9'

services:
  backend:
    build: ./backend
    container_name: mail-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - spacy_data:/usr/local/lib/python3.11/site-packages/fr_core_news_sm
      - ./logs:/app/logs
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mail-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  spacy_data:


